### ISSUE TITLE
New Contact Us form using google sheets 

### ISSUE THREAD

**Issue by PrabirKalwani** [PrabirKalwani/classes_template#12]

**Comment by Shivansh-2508** [comment]
Sheet link:- https://docs.google.com/spreadsheets/d/184ASPgPZM2oQ9BEfUpaaBgj8ODBggliN30l0_0Z0hTw/edit#gid=0
API link:-  https://sheet.best/api/sheets/82fcd852-d325-4f16-b4ff-82d7e62bebca
